name: Mac2FA
targets:
  Mac2FA:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Mac2FA
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.mac2fa
      INFOPLIST_FILE: Mac2FA/Info.plist
      CODE_SIGN_ENTITLEMENTS: Mac2FA/Mac2FA.entitlements
      ENABLE_HARDENED_RUNTIME: YES
      SWIFT_VERSION: "6.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies: []
  Mac2FATests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Mac2FATests
    dependencies:
      - target: Mac2FA
    settings:
      SWIFT_VERSION: "6.0"
      INFOPLIST_FILE: Mac2FATests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: app.mac2fa.tests
